### ISSUE TITLE
Ignore files under *test* folders

### ISSUE THREAD

**Issue by Postyy** [jfrog/jfrog-vscode-extension#11]
Related PR: https://github.com/jfrog/jfrog-vscode-extension/pull/9

**Comment by Postyy** [comment]
Active `*test*` by default could hit many scenarios which can lead to unsecured behavior.
We can add to each 'excluded director', a yellow icon in the project's dependency tree to clear up the situation.

**Comment by yahavi** [comment]
Indeed. But 'testdir' is too specific. That's why it has to be configurable. See the default here: https://github.com/jfrog/jfrog-vscode-extension/pull/13/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R57
