### ISSUE TITLE
Support Projects in vscode

### ISSUE THREAD

**Issue by colts45s** [jfrog/jfrog-vscode-extension#152]
Integration with Projects not supported.
IntelliJ IDEA has the ability to link to a project key, but does not seem to be available in vs code.

**Comment by yahavi** [comment]
@colts45s,
Thanks for using the JFrog VS-Code extension.

The ability to link a project key was added in version 1.10.0.
To configure a project key, go to the [extension settings](https://github.com/jfrog/jfrog-vscode-extension#extension-settings) and set your project key:
![image](https://user-images.githubusercontent.com/11367982/152407999-5861b6a6-7dd8-4487-97cc-e23712de4950.png)

For more information see [Applying Your Xray Policies](https://github.com/jfrog/jfrog-vscode-extension#applying-your-xray-policies).
Please let me know if that helped. 
We'd also appreciate your feedback on this feature and on the extension in general.

**Comment by colts45s** [comment]
Appreciate the information. I had assumed the option would be available during the configuration steps but I do see this now and will close the feature request.
