### ISSUE TITLE
JFrog IDE plugin scan fails on Windows due to whitespace in username

### ISSUE THREAD

**Issue by srmish-jfrog** [jfrog/jfrog-vscode-extension#354]
**Describe the bug**
When scanning a project in JFrog IDE plugin latest version, the scan fails on Windows because there is " missing in the -Dfile argument -
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/92059693/0f94bb15-6d8d-430e-83a9-8bc85b25eb3c)

The argument used -
`-Dfile=c:\Users\Shachar Menashe\.vscode\extensions\jfrog.jfrog-vscode-extension-2.3.1\resources\maven-gav-reader.jar`

The argument that should be used -
`-Dfile="c:\Users\Shachar Menashe\.vscode\extensions\jfrog.jfrog-vscode-extension-2.3.1\resources\maven-gav-reader.jar"`

**To Reproduce**
Using IDE Plugin 2.3.1, Connected to Xray 3.74.8, scan the following project in the IDE -
https://github.com/WebGoat/WebGoat

Observe that the scan crashes on an Exception (see screenshot)

**Expected behavior**
Scanning the WebGoat project should completely successfully without a crash

**Versions**
- JFrog IDEA plugin version: 2.3.1
- Operating system: Windows 10 Pro 22H2 19045.2965
- Xray version: 3.74.8

**Comment by attiasas** [comment]
Hi, thank you for reporting this issue.
Fix will be included in this [PR](https://github.com/jfrog/jfrog-vscode-extension/pull/353) and will be included in the next release.
