### ISSUE TITLE
[go:embed] Unable to get golang project using go:embed module to properly scan

### ISSUE THREAD

**Issue by pizzqc** [jfrog/jfrog-vscode-extension#372]
**Describe the bug**
When trying to scan for xray vulnerabilities, if the golang project uses `//go:embed` notation, the scan fails to find the file resource properly.. leading to go.mod to be flag `has error`

**To Reproduce**
1. create subfolder `config` with file `configStruct.go` as part of `package config`
```
package config

import (
	_ "embed"
)

//go:embed version.txt
var buildVersion string
```
3. Add the file `version.txt` under the `config` folder.  Just beside the `configStruct.go` file
4. Run the jfrog xray scan

Error:
```
[ERR - 1:39:05 PM] Error: Command failed: go list -f "{{with .Module}}{{.Path}} {{.Version}}{{end}}" all
config\configStruct.go:8:12: pattern version.txt: no matching files found
```

**Expected behavior**
The file `version.txt` is present and should be found.

**Versions**
- JFrog VS-Code extension version: `v2.3.4`
- JFrog VS-Code extension operating system: `Windows 10`
- JFrog Xray Version: `3.76.7`

**Comment by pizzqc** [comment]
I believe the issue is here: https://github.com/jfrog/jfrog-vscode-extension/blob/master/src/main/utils/goUtils.ts#L222  where a workspace destination folder is use to do the scan -- and where only the `*.go` and the `go.mod` are copied... resulting in missing embedded resources files to be present and thus leading to the error mention in this bug.

The workspace where stuff are copied to should probably allow it to be either all files or allow plugin to be configured to include more patterns to be copied over?  

Any though?

**Comment by Or-Geva** [comment]
@pizzqc, the JFrog VS Code Extension V2.9.0 has been released, addressing the mentioned issue. We welcome your feedback on the latest update.

**Comment by pizzqc** [comment]
Tested using extension version `v2.9.0` and it is completing the analysis properly now.  Thanks for the fix.
