### ISSUE TITLE
extension not visible on sidebar after installation

### ISSUE THREAD

**Issue by adoniadi-stm** [jfrog/jfrog-vscode-extension#401]
**Describe the bug**
After installing the Jfrog extension v 2.5.0 on vs studio, the extension icon is not visible on the side bar

**To Reproduce**
Try installing extension v2.5.0 or any version >= v2.2.0

**Expected behavior**
The sidebar should be displaying the extension icon

**Screenshots**
![image](https://github.com/jfrog/jfrog-vscode-extension/assets/126658566/e345eb52-3285-4d07-b97f-0f2587de3b2b)

**Versions**
- JFrog VS-Code extension version: 2.5.0
- JFrog VS-Code extension operating system: Windows 10
- JFrog Xray Version: 7.41.7

**Additional context**
with versions up to 2.1 the icon is displayed

**Comment by adoniadi-stm** [comment]
Hi
Thanks for responding so promptly 😊
As you can see below, it is not visible on the side panel nor on right-click, however it is installed

***@***.***

By the way, I saw a error (e.setKeepAlive is not a function) on the runtime Status

***@***.***

Cheers
Kirk


***@***.***

Kirk ADONIADIS
DTIT | CAD & Software Engineering Factory
Tel: +041 4475 | Mobile: +33 674685830

**Comment by Or-Geva** [comment]
@adoniadi-stm, we just released JFrog VS-Code extension 2.8.2, which fixes this issue. Please let me know if it works for you.
