### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by gpant** [jfrog/jfrog-vscode-extension#70]
**Describe the bug**
Everytime I start vscode with a go project I get this:
Error: Request failed with status code 404
and obviously no feature for the extension is functional.

**To Reproduce**
Start vscode

**Expected behavior**
working extension

**Screenshots**
https://i.imgur.com/yUW5PSY.png

**Versions**
- JFrog VS-Code extension version: 1.5.1
- JFrog VS-Code extension operating system: Windows(10.2004) , Linux(Fedora.32)
- JFrog Xray Version: 

**Additional context**

**Comment by yahavi** [comment]
Thanks for reporting this issue, @gpant.
I looked into it and apparently, the GoCenter REST API returns 404.
We are working hard to resolve this quickly.
We'll keep you updated.

**Comment by ankushchadha** [comment]
The issue has been identified and the fix has been tested on pre-prod environments. The fix will be deployed tonight pacific time. 

In addition, we identified that there were some annotations set that prevented specific tests to execute that would have detected this regression. The team removed that specific annotation and made sure that we don't have a similar problem elsewhere.

**Comment by ankushchadha** [comment]
A fix was pushed to [GoCenter](https://search.gocenter.io). Can you try again? HTTP 404s shouldn't be observed. We have also taken steps to avoid regressions for such use cases going forward.

**Comment by gpant** [comment]
Just tested it and it works perfectly fine now.
