### ISSUE TITLE
Python: Xray fails with "Please install a virtual environment" with venv activated

### ISSUE THREAD

**Issue by ducoterra** [jfrog/jfrog-vscode-extension#73]
After connecting to my Xray instance successfully and initiating a scan I get an error that claims I don't have a virtual environment installed. Full error is:

```bash
Please install and activate a virtual environment before running Xray scan. Then, install your Python project in that environment.
```

My virtual environment is named 'venv' and lives at the root of my project. I have it selected as my virtual environment per VSCode's instructions and have pip installed all packages to that environment. Debug log from JFrog as follows:

```bash
[INFO - 3:56:52 PM] Starting slow scan
[INFO - 3:56:52 PM] Locating go.mod files in workspace "workspace".
[DEBUG - 3:56:53 PM] No go.mod files found in workspaces.
[INFO - 3:56:53 PM] Locating package json files in workspace "workspace".
[DEBUG - 3:56:53 PM] No package.json files found in workspaces.
[INFO - 3:56:53 PM] Locating python files in workspace "workspace".
[DEBUG - 3:56:53 PM] Detected python files in workspace workspace: [file:///project/directory/requirements.txt]
[INFO - 3:56:53 PM] Locating pom.xml files in workspace "workspace".
[DEBUG - 3:56:53 PM] No pom.xml files found in workspaces.
[INFO - 3:56:53 PM] Locating *.sln files in workspace "workspace".
[DEBUG - 3:56:53 PM] No *.sln files found in workspaces.
```

I thought I followed the instructions in the README correctly. Any thoughts on why this might be happening?

**Comment by yahavi** [comment]
@ducoterra 
Please make sure to activate your venv as follows:
1.
![image](https://user-images.githubusercontent.com/11367982/94988539-b53ebe80-0576-11eb-81e8-3c8141fa7284.png)
2.
![image](https://user-images.githubusercontent.com/11367982/94988559-e28b6c80-0576-11eb-9c35-b9efbda7f633.png)

Please let me know if it helped. 
We'd also appreciate any other feedback about the extension and its instructions.

**Comment by ducoterra** [comment]
That's the issue, I do have my virtual environment activated like that. The xray plugin doesn't seem to recognize it.

**Comment by ducoterra** [comment]
Are there logs I can provide that would help identify the issue?

**Comment by yahavi** [comment]
Thanks, @ducoterra.
To figure our whether the current Python project is running under Virtualenv, we run [this](https://github.com/jfrog/jfrog-vscode-extension/blob/master/resources/python/checkVenv.py) script in the root folder of the project: 
```python
import sys

virtualenv_prefix = getattr(sys, "real_prefix", None)
venv_prefix = getattr(sys, "base_prefix", sys.prefix)
if virtualenv_prefix or venv_prefix != sys.prefix:
    exit(0)

exit(1)

```
For more information about this attitude, read here: https://stackoverflow.com/a/58026969/4233342

Can you please give it a try in your environment? You can try to run this as follows:
```sh
# Before activating the environment
python checkVenv.py
echo $?
# response code should be 1 because the Virtualenv is not activated

# Activate env
source venv/bin/activate
python checkVenv.py
echo $? 
# response code should be 0. What do you see here?
```

Can you please also provide more information about your environment? This information must include your operating system, virtual environment type and version. Are you using Anaconda virtualenv?

Looking forward to your feedback!

**Comment by ducoterra** [comment]
Thanks for the details! Here are my specs:

OS: macOS Catalina version 10.15.7 (19H2)
Python version: 3.8.3
Virtual environment type: might need some help answering this. It's not Anaconda. I ran `python3 -m venv venv` to create it.

I ran the script and got the expected output:
```
user@laptop project_dir % python3 checkVenv.py 
user@laptop project_dir % echo $?
1
user@laptop project_dir % source venv/bin/activate
(venv) user@laptop project_dir % python3 checkVenv.py 
(venv) user@laptop project_dir % echo $?
0
```

Appreciate the help.

**Comment by yahavi** [comment]
@ducoterra,
Thanks for your inputs.

I created #75 to help investigating this issue further.

**Comment by yahavi** [comment]
@ducoterra 
We release JFrog VS-Code extension 1.5.2. In this version, when the extension fails to run `checkVenv.py` in the virtualenv, it prints the reason to the logs.

Looking forward to your feedback!

**Comment by rderveloy** [comment]
I'm having the same exact issue as @ducoterra as well.  I'm running version 1.7.0 of the extension in VS Code 1.55.0 on MacOS 10.15.7.  I have verified that the virtual environment is activated, that dependencies are installed, and that the virtual environment is selected in VS Code per the instructions on the extension's detail page:

```
Command failed: python /Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/resources/python/checkVenv.py
Error: Command failed: python /Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/resources/python/checkVenv.py
	at checkExecSyncError (child_process.js:639:11)
	at Object.execSync (child_process.js:675:15)
	at Object.execSync (electron/js2c/asar_bundle.js:5:12113)
	at Function.isInVirtualEnv (/Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/out/main/utils/pypiUtils.js:91:18)
	at Function.createDependenciesTrees (/Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/out/main/utils/pypiUtils.js:67:28)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Function.createDependenciesTrees (/Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/out/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.js:13:13)
	at async /Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/out/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.js:151:13
	at async /Users/-----/.vscode/extensions/jfrog.jfrog-vscode-extension-1.7.0/out/main/utils/scanUtils.js:22:13
```

I also get a result of 0 when running checkVenv.py with the virtual environment activated and a 1 if it's not activated.  If there are log files, can you tell me where to find them so I can include them here?

Running checkVenv.py through a debugger, it seems that virtualenv_prefix is being set to None and venv_prefix is being set to '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8', which is not the project's activated virtual environment.  The correct virtual environment is returned by sys.prefix:

```
(venv) laptop:test -----$ python
Python 3.8.2 (default, Aug 25 2020, 09:23:57) 
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.prefix)
/Users/-----/VS Code Projects/test/venv
```

I'm wondering if there might be a bug in `isInVirtualEnv()` or `getPythonPath()` in pypiUtils.ts since `isInVirtualEnv()` is obviously returning a false value given the following error message:
`Please install and activate a virtual environment before running Xray scan. Then, install your Python project in that environment.`

**Comment by mlieberman85** [comment]
I'm also running into the same issue as @rderveloy and @ducoterra.

**Comment by DrackThor** [comment]
me too, exactly the same behavior!
I am using [pyenv](https://github.com/pyenv/pyenv) with [pyenv-virtualenvwrapper](https://github.com/pyenv/pyenv-virtualenvwrapper) with Python 3.9.1

**Comment by yahavi** [comment]
@mlieberman85 @rderveloy @DrackThor 
Thanks for your feedback. 
We currently support only Virtualenv.

However, we plan to change, in the near future, the way we calculate the Python dependencies to better interact with the [vscode-python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension. This extension contains all the information we need to properly build the dependency tree in all environments. 🚀 
One direction we will start to investigate soon is to [contribute an API](https://github.com/microsoft/vscode-python/blob/main/src/client/api.ts#L22) that exposes the needed information.

We'll keep you updated once a better solution will be found.

**Comment by yahavi** [comment]
@ducoterra @rderveloy @mlieberman85,
JFrog VS-Code extension 1.8.5 is released! On this version we retrieve the Python executable path in a better way - see https://github.com/jfrog/jfrog-vscode-extension/pull/127.
Feel free to upgrade - we'd appreciate your feedback on that.

@DrackThor - currently only Virtualenv is supported by the extension.
