### ISSUE TITLE
How do we know the URL of Xray server - JFrog artifactory 7.7.3

### ISSUE THREAD

**Issue by rmkanda** [jfrog/jfrog-vscode-extension#78]
We are running JFrog artifactory 7.7.3 which has integrated xray.
Let's say our URL is  https://artifactory.test.com/
What will be the URL for xray?

**Comment by yahavi** [comment]
@rmkanda 
The answer depends on your Xray server configuration.
Typically for SaaS users `https://<jfrog-url>/xray` or, in your case `https://artifactory.test.com/xray`.

If it doesn't work, as Artifactory admin user, you can find Xray base URL by retrieving [Arifactory's general configuration](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-GeneralConfiguration).
For example:
```
jfrog rt curl /api/system/configuration
```

Response:
```xml
<config xmlns="http://artifactory.jfrog.org/xsd/3.1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jfrog.org/xsd/artifactory-v3_1_1.xsd">
...
    <xrayConfig>
        ...
        <baseUrl>This is Xray URL</baseUrl>
...
</config>
```

Please let me know if it helped.

**Comment by rmkanda** [comment]
Thanks @yahavi

**Comment by lysov** [comment]
As a non-admin SaaS user, I was able to retrieve a list of server URLs (e.g., Xray and Artifactory) using CLI v2.

```sh
jf config show
```
