### ISSUE TITLE
Jfrog Visual Studio Code not scanning Libraries

### ISSUE THREAD

**Issue by bhupi-cloudeq** [jfrog/jfrog-vscode-extension#99]
I have added Jfrog extension in VSCode and connected with Jfrog Instance. When I start scanning it starts scanning then shows 404 error.

ScreenShot attached

![image](https://user-images.githubusercontent.com/73111511/112302706-60783700-8cc1-11eb-89b5-11a7e0edcf08.png)

![image](https://user-images.githubusercontent.com/73111511/112302727-6837db80-8cc1-11eb-8c5e-e72aab8c6aa9.png)

**Comment by yahavi** [comment]
@bhupi-cloudeq,
Thanks for reporting this issue.
Could you please share the extension's logs?
You can see them after clicking on the "JFrog" button:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/11367982/112308145-7af2e600-8caa-11eb-9705-40a0d3b6bfeb.png">

**Comment by bhupi-cloudeq** [comment]
Thanks for early reply
Below are the logs

[INFO - 5:55:05 pm] Starting slow scan
[INFO - 5:55:05 pm] Locating go.mod files in workspace "ceq-webapi-core".
[DEBUG - 5:55:06 pm] No go.mod files found in workspaces.
[INFO - 5:55:06 pm] Locating package json files in workspace "ceq-webapi-core".
[DEBUG - 5:55:06 pm] No package.json files found in workspaces.
[INFO - 5:55:06 pm] Locating python files in workspace "ceq-webapi-core".
[DEBUG - 5:55:07 pm] No setup.py and requirements files found in workspace ceq-webapi-core.
[INFO - 5:55:07 pm] Locating pom.xml files in workspace "ceq-webapi-core".
[DEBUG - 5:55:07 pm] No pom.xml files found in workspaces.
[INFO - 5:55:07 pm] Locating *.sln files in workspace "ceq-webapi-core".
[DEBUG - 5:55:07 pm] Solution files to scan: [[file:///d%3A/Practice-git/ceq-webapi-core/ceq-webapi-core.sln]]

**Comment by yahavi** [comment]
Thanks, @bhupi-cloudeq.
Could you please try to disconnect and reconnect? While doing so, please look at the logs. Make sure the platform URL is accessible for browsing.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/11367982/112311993-fbb3e100-8cae-11eb-9009-e224ba11a9ee.png">

Additionally, you can check the Xray URL printed in the logs by running the following curl command and make sure you get a list of issues and licenses for a Go package:
```sh
curl -XPOST https://<jfrog-platform>/xray/api/v1/summary/component -u<user>:<password> -H "Content-Type: application/json" --data '{"component_details": [{"component_id": "go://github.com/containous/traefik:1.7.0"}]}'
```

Please let me know if it helped.

**Comment by bhupi-cloudeq** [comment]
Logs are same but reconnecting worked ,I did it earlier also ,but this time reconnecting worked

![image](https://user-images.githubusercontent.com/73111511/112317522-29f6e800-8cd2-11eb-997e-06da399e9108.png)

**Comment by yahavi** [comment]
@bhupi-cloudeq 
I'm glad to hear it works now.
It sounds like your Xray instance wasn't available for some reason.

Please let us know if encounter this issue again in the future.
